### ISSUE TITLE
[Feature Request]: Problem in landing page. No route work

### ISSUE THREAD

**Issue by Suvadip-sana** [Soujanya2004/wanderlust-2024#410] opened 2024-11-05 14:41 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Feature Description

In landing page all the field that supposed to be linked with existing route your back end have. But no route is added. Every route say `No page found`

You can verify that in attached video.

### Use Case

I would fix that ISSUE, in all over your landing page.
I add all possible link that need in landing page.

@Soujanya2004  Assign it to me.

### Add ScreenShots

https://github.com/user-attachments/assets/438302ea-e9d5-437b-a1ce-9a258321a944

### Priority

High

### Record

- [X] I have read the Contributing Guidelines
- [X] I'm a GSSOC'24 contributor
- [X] I have starred the repository

**Comment by Soujanya2004** [comment] 2024-11-05 14:48
@dev129 are you solving it or shall i assign it to others

**Comment by dev129** [comment] 2024-11-05 14:49
Assign me for the next 24 hours if bit able to solve then give ut to next person

**Comment by Suvadip-sana** [comment] 2024-11-05 14:51
@Soujanya2004 

Yes assign him. It's his part

**Comment by Suvadip-sana** [comment] 2024-11-05 14:52
But please try to solve it faster because it stop for working on other ISSUE @dev129

**Comment by Soujanya2004** [comment] 2024-11-05 14:52
> Assign me for the next 24 hours if not able to solve then give it to next person, I will try to disturb you tomorrow at 3 pm

😅sure but please make it asap

**Comment by dev129** [comment] 2024-11-05 16:03
https://github.com/user-attachments/assets/050afe2b-1991-48cc-9cf6-22af47d1e322

I tried making the route work , the only thing is some developement has to be done as the listing section is still incomplete , and hence the person is being redirected to landing page 
It is a bug which I might be able tol solve , if i could.

**Comment by Soujanya2004** [comment] 2024-11-05 16:05
@dev129 yes please try solving it
and also one of the heading is not properly visible in dark mode please change that

**Comment by Suvadip-sana** [comment] 2024-11-05 17:35
@dev129  Prioritize this ISSUE. Because this is the ISSUE which affect all other development. Please try to understand this.

**Comment by dev129** [comment] 2024-11-05 17:37
@Suvadip-sana , you need to understand that @Soujanya2004 , has already rolled back , secondly I am already working on this issue, I know it needs to be resolved at the earliest.

**Comment by dev129** [comment] 2024-11-05 18:07
@Soujanya2004 , I know its too late but the issue is successfully solved. 

https://github.com/user-attachments/assets/34bd5d8d-9a3e-4517-8f88-5d6bbb86f2f9

**Comment by Soujanya2004** [comment] 2024-11-06 01:55
👍🏻👍🏻

**Comment by Soujanya2004** [comment] 2024-11-06 02:02
@dev129 raise pr 
Hope u have git pull before solving this

**Closed** 2024-11-06 14:38 UTC
Labels: gssoc-ext, level1

**Comment by dev129** [comment] 2024-11-08 07:56
Hi @Soujanya2004 , I am not abel to see the chnges I made , plesase chekc once 
![image](https://github.com/user-attachments/assets/3fa4ba20-c464-4a61-8c66-ede432abbcf5)
I have performed the git pul origin main , done sync also
